[package]
name = "chip8"
version = "0.1.0"
authors = ["Tyler Oalman <tyleroalman@gmail.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.1"
flexi_logger = "0.15.2"
log = { version = "0.4.8", features = ["release_max_level_warn"] }
